accepted_risk: [0.5]

n_epochs: 200
n_steps: 5000

atacom_lam: 3.0
atacom_beta: [3]
cost_budget: 0

learning_rate_constraint: [5.e-4]

learning_rate_actor: 1.e-3
learning_rate_critic: 1.e-3

lr_alpha: [1.e-3]
target_entropy: [0.5]

use_cuda: False
