accepted_risk: [0.9]

n_epochs: 100
n_steps: 10000

atacom_lam: 25
atacom_beta: 1

cost_budget: 15

initial_replay_size: 10000
warmup_transitions: 10000
max_replay_size: 200000

learning_rate_constraint: 1.e-4

learning_rate_actor: 1.e-4
learning_rate_critic: 1.e-4

lr_alpha: 1.e-4
target_entropy: -2
batch_size: 64

use_cuda: False

render: False
n_episodes_test: 10
init_delta: 3
lr_delta: 0.05
delta_warmup_transitions: 50000