accepted_risk: [ 0.9 ]

n_epochs: 100
n_steps: 30000

atacom_lam: 25
atacom_beta: 1

cost_budget: [ 25 ]

initial_replay_size: 10000
warmup_transitions: 10000
max_replay_size: 1000000

learning_rate_constraint: 1.e-3

learning_rate_actor: 1.e-3
learning_rate_critic: 1.e-3

lr_alpha: 1.e-3
target_entropy: -2
batch_size: 256

render: False
n_episodes_test: 10

init_delta: 3
lr_delta: 0.05
delta_warmup_transitions: 10000

n_features_actor: '128 128 128'
n_features_critic: '128 128 128'
n_features_constraint: '128 128 128'

use_cuda: True