n_epochs: 100
n_steps: 10000

lr_alpha: [1.e-4]

learning_rate_constraint: 1.e-4

learning_rate_actor: 1.e-4
learning_rate_critic: 1.e-4

accepted_risk: [0.5]
atacom_lam: 30.0
atacom_beta: [1]
cost_budget: 0

target_entropy: [-2]

use_cuda: False
init_delta: 3
lr_delta: 0.05
delta_warmup_transitions: 50000