accepted_risk: 0.9

n_epochs: 100
n_steps: 10000

initial_replay_size: 2000
warmup_transitions: 2000
max_replay_size: 200000
batch_size: 64

atacom_lam: 60
atacom_beta: 3
cost_budget: 40

learning_rate_constraint: 5.e-4

learning_rate_actor: 5.e-4
learning_rate_critic: 5.e-4

lr_alpha: 5.e-4
target_entropy: -1

init_delta: 6
lr_delta: 0.05
delta_warmup_transitions: 50000

use_cuda: False
