lr_beta: 5.e-4
cost_limit: 0
damp_scale: 1
learning_rate_constraint: 5.e-4

n_epochs: 100
n_steps: 10000

max_replay_size: 200000

learning_rate_actor: 5.e-4
learning_rate_critic: 5.e-4

lr_alpha: 5.e-4
target_entropy: -3

