n_epochs: 100
n_steps: 10000
lr_alpha: 1.e-4
lr_beta: 1.e-4

target_entropy: [-2]

cost_limit: 0
damp_scale: [1]

constraint_max_size: 200000
max_replay_size: 200000

learning_rate_constraint: 1.e-4

learning_rate_actor: 1.e-4
learning_rate_critic: 1.e-4

