lr_beta: 5.e-4
cost_limit: 0
damp_scale: [0]
learning_rate_constraint: [5.e-4]

n_epochs: 1000

max_replay_size: 200000

learning_rate_actor: 1.e-3
learning_rate_critic: 1.e-3

lr_alpha: 1.e-3
target_entropy: 0.5

