lr_beta: 1.e-3
cost_limit: 0
damp_scale: [0.0]
learning_rate_constraint: 1.e-3

n_epochs: 1000
accepted_risk: [0.1, 0.5, 0.9]

constraint_max_size: 200000
max_replay_size: 200000

learning_rate_actor: 1.e-3
learning_rate_critic: 1.e-3
lr_alpha: 1.e-3
target_entropy: [0.5]

constraint_type: "gaussian"
